name: jam_sholat_tv
description: "Jam Sholat TV"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  wakelock_plus: ^1.2.8
  dio: ^5.4.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  marquee: ^2.2.3
  audioplayers: ^6.5.1
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.4
  hijriyah_indonesia: ^0.1.7
  flutter_svg: ^2.2.3
  youtube_player_flutter: ^9.1.3
  provider: ^6.1.5+1
  logger: ^2.5.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"
